language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install --server=http://luarocks.org/dev openssl
  - luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  - luarocks install luafilesystem
  - luarocks install busted
  - luarocks install rapidjson
  - luarocks install luacrypto
  - luarocks install date

script:
  - busted spec

notifications:
  email:
    on_success: change
    on_failure: always
