language: erlang

env:
  - LUA="luajit" LUA_PATH="lib/?.lua;;"

branches:
  only:
    - master

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks install --server=http://luarocks.org/dev openssl
  - sudo luarocks install luasec OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install rapidjson
  - sudo luarocks install luacrypto
  - sudo luarocks install date

script: "busted spec"
